name: Snyk Security Scan # Name of this GitHub Actions workflow

on:
    push:
        branches: [main, develop] # Run on push events to main and develop branches
    pull_request:
        branches: [main, develop] # Run on pull requests targeting main and develop branches

jobs:
    security:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner for the job
        steps:
            - uses: actions/checkout@v4 # Step 1: Check out the repository code

            - name: Install dependencies
              run: npm ci # Step 2: Install all dependencies using npm ci for a clean and reproducible install

            - name: Snyk Test (Vulnerability Scan)
              uses: snyk/actions/node@main # Step 3: Run Snyk's official GitHub Action (Node.js version, specify action version)
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Provide the Snyk authentication token from GitHub Secrets
              with:
                  args: --severity-threshold=high # Only fail if vulnerabilities of "high" severity or above are found

            - name: Snyk Monitor (Send to Dashboard)
              uses: snyk/actions/node@main # Step 4: Send the dependency snapshot to Snyk's dashboard for continuous monitoring
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Provide the Snyk authentication token from GitHub Secrets
              with:
                  command: monitor # Use the "monitor" command to upload dependency information to Snyk
